#INCLUDE <STDIO.H>
#INCLUDE <STDLIB.H>
INT
MAIN(INT ARGC, CHAR * * ARGV)
{
  IF (ARGC < 2)
    {
      PRINTF("NEED A NUMBER\N");
      RETURN EXIT_FALIURE;
    }
  INT VAL = STRTOL(ARGV[1], NULL, 10);
  VAL += 10;
  PRINTF("ARGV[1] = %S\N", ARGV[1]);
  PRINTF("VAL = %D\N", VAL);
  RETURN EXIT_SUCCESS;
}